### ISSUE TITLE
Descrever melhor o componente mais interativo.

### ISSUE THREAD

**Issue by matheusgr** [viniciusbds/devweb#1]
Podes descrever melhor qual seria e como funcionaria o componente com mais interatividade?

**Comment by viniciusbds** [comment]
@matheusgr dei uma atualizada na descrição, mas posso melhorar ela se preciso. 
A idea era ter um componente interativo que mostrasse informações da aposta antes do usuário apostar de fato. 
as informações seriam:
         - a porcentagem de retorno caso ganhe a aposta naquele instante
         - e a quantidade de apostas feitas em cada um dos times. ex time1=60% das apostas e time2=40%
