### ISSUE TITLE
Tela com todas as apostas de um time

### ISSUE THREAD

**Issue by caio-fm** [viniciusbds/devweb#3]
Acho que seria legal ter alguma forma de clicar em um time e conseguir ver todas as apostas (em progresso e já encerradas) das partidas envolvendo esse time.

**Comment by viniciusbds** [comment]
valeu pelo feedback @caio-fm , essa é a ideia. A aplicação principal terá uma listagem de apostas, na qual será possível filtrar por jogos e times, ai o usuario seleciona uma partida e faz sua aposta
