### ISSUE TITLE
Usar somente um gerenciador de pacotes

### ISSUE THREAD

**Issue by mathsantana** [viniciusbds/devweb#5]
No frontend, há tanto o arquivo do npm, `package-lock.json`, quanto o arquivo do yarn, `yarn.lock`. O uso dos dois gerenciadores pode causar problemas na árvore de dependências e é desencorajado. É indicado que se faça o uso consistente de somente um. Eu sugiro que:

1. Exclua os arquivos `package-lock.json` e `yarn.lock` e a pasta `node_modules`, para garantir que não haja diferenças na árvore de dependências.
2. Use um dos dois gerenciadores de pacotes: `npm install` ou `yarn`.

Há também a possibilidade do yarn importar as dependências do `package-lock.json` usando o comando `yarn import` como explicado nesse [artigo](https://classic.yarnpkg.com/blog/2018/06/04/yarn-import-package-lock/).

**Comment by viniciusbds** [comment]
valeu pela dica @mathsantana, ja fiz a alteração e subi p/ master
